# openshift-install explain installconfig  
#
# https://docs.openshift.com/container-platform/4.11/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html
apiVersion: v1
baseDomain: ${cluster_domain}
%{ if httpsProxy != "" }
proxy:
  httpProxy: ${httpsProxy} 
  httpsProxy: ${httpsProxy} 
%{ if noProxy != "" }
  noProxy: ${noProxy} %{ endif }%{ endif }
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0 # TODO : Length from terraform?
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3  # TODO : Length from terraform?
metadata:
  name: ${name}
platform:
  vsphere:
    vcenter: ${vc}
    username: ${vc_username} # administrator@vsphere.lan
    password: ${vc_password}
    datacenter: ${vc_datacenter}
    defaultDatastore: ${vc_defaultDatastore}
    # https://docs.openshift.com/container-platform/4.11/installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.html
    # apiVIP: ${apiVIP} # 128.0.0.1 # TODO The virtual IP (VIP) address that you configured for control plane API access.
    # ingressVIP: ${ingressVIP} # 129.0.0.1 TODO # The virtual IP (VIP) address that you configured for cluster ingress.
    # vcenter: 192.168.1.240
    # username: administrator@vsphere.lan
fips: false
# The pullSecret configuration setting contains a copy of the pull secret downloaded from the Install OpenShift on Bare Metal page when preparing the provisioner node. 
pullSecret: '${pullSecret}'
# The sshKey configuration setting contains the key in the ~/.ssh/id_rsa.pub file required to access the control plane nodes and worker nodes. Typically, this key is from the provisioner node.
sshKey: '${sshKey}'
# https://docs.openshift.com/container-platform/4.10/rest_api/machine_apis/controllerconfig-machineconfiguration-openshift-io-v1.html
#additionalTrustBundle: |
#  -----BEGIN CERTIFICATE-----
#  ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
#  -----END CERTIFICATE-----