config:
  runStrategy:
    runs: 1
    maxSecondsBetweenRuns: 10
    minSecondsBetweenRuns: 1
scenarios:
  - name: "check 2 pods are in namespace with selector: prometheus"
    steps:
    - podAction:
        matches:
          - labels:
              namespace: "openshift-monitoring"
              selector: "app=prometheus"
        filters:
          - property:
              name: "state"
              value: "Running"
        # The actions will be executed in the order specified
        actions:
          - checkPodCount:
              count: 2
